apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "hpa-scaler.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["hpa"]
  verbs: ["get", "watch", "list", "update"]