apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hpa-scaler.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: {{ include "hpa-scaler.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "hpa-scaler.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io